## Write a Numpy program to compute the multiplication of two given matrixes

In [13]:
import numpy as np
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[1,2,3],[4,5,6]])

In [14]:
mat1*mat2

array([[ 1,  4,  9],
       [16, 25, 36]])

## Write a NumPy program to compute the determinant of a given square array

In [15]:
mat3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(mat3)

6.66133814775094e-16

## Write a NumPy program to compute the cross product of two given vectors

In [19]:
np.cross(mat1,mat1)

array([[0, 0, 0],
       [0, 0, 0]])

## Write a NumPy program to compute the condition number of a given matrix

In [21]:
np.linalg.cond(mat1)

12.302245504069205

## Write a NumPy program to compute the inverse of a given matrix

In [23]:
    np.linalg.inv(mat3)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])